name: Build
on:
  workflow_dispatch:
jobs:
  build_ios:
    permissions:
      contents: write
    runs-on: macos-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          repository: 'RazrFalcon/resvg'
          fetch-depth: 0

      - name: Get the latest tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV
      - name: Checkout latest tag
        run: git checkout ${{ env.latest_tag }}

      - name: Build c-api
        run: |
          cd crates/c-api
          rustup target add aarch64-apple-ios aarch64-apple-ios-sim
          cargo build --target aarch64-apple-ios --release --no-default-features
          cargo build --target aarch64-apple-ios-sim --release --no-default-features

      - name: Lipo
        run: |
          lipo -create \
          target/aarch64-apple-ios/release/libresvg.a \
          target/aarch64-apple-ios-sim/release/libresvg.a \
          -output libresvg.a

      - name: Zip
        run: zip libresvg.zip libresvg.a
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.latest_tag }}
          files: libresvg.zip

  # build_android:
  #   permissions:
  #     contents: write
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout the repository
  #       uses: actions/checkout@v4
  #       with:
  #         repository: 'RazrFalcon/resvg'
  #         fetch-depth: 0

  #     - name: Get the latest tag
  #       run: |
  #         latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
  #         echo "Latest tag: $latest_tag"
  #         echo "latest_tag=$latest_tag" >> $GITHUB_ENV
  #     - name: Checkout latest tag
  #       run: git checkout ${{ env.latest_tag }}

  #     - name: Install Android NDK
  #       run: |
  #         wget -nv https://dl.google.com/android/repository/android-ndk-r27-linux.zip
  #         unzip -qq android-ndk-r27-linux.zip
  #         mv android-ndk-r27 android-ndk
  #         echo "CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=$(pwd)/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android35-clang" >> $GITHUB_ENV

  #     - name: Build c-api
  #       run: |
  #         cd crates/c-api
  #         rustup target add aarch64-linux-android
  #         cargo build --target aarch64-linux-android --config target.aarch64-linux-android.linker=\"$CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER\" --release --no-default-features

  #     - name: Upload artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: libresvg.so
  #         path: target/aarch64-linux-android/release/libresvg.so

