name: Build
on:
  workflow_dispatch:
jobs:
  build:
    permissions:
      contents: write
    runs-on: macos-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          repository: 'RazrFalcon/resvg'
          fetch-depth: 0

      - name: Get the latest tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV
      - name: Checkout latest tag
        run: git checkout ${{ env.latest_tag }}

      - name: Build c-api
        run: |
          cd crates/c-api
          rustup target add aarch64-apple-ios
          cargo rustc --target aarch64-apple-ios --release --no-default-features -- --crate-type staticlib
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.latest_tag }}
          files: target/aarch64-apple-ios/release/libresvg-capi.a